/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.brasil.petshop;

import com.brasil.petshop.controller.CadastroAnimalViewController;
import com.brasil.petshop.model.Animal;
import com.brasil.petshop.model.Cliente;
import com.brasil.petshop.model.Raca;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author User
 */
public class CadastroAnimalView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroAnimalView
     */
    private Connection connection;
    private CadastroAnimalViewController controller;
    private Animal animal = new Animal();
    private boolean isEdicao = false;
    
    public CadastroAnimalView(Connection connection, Animal animal) {
        initComponents();
        jTextFieldCodigoAnimal.setEnabled(false);
        this.connection = connection;
        controller = new CadastroAnimalViewController(connection);
        carregarRacas();
        carregarClientes();
        
        if (animal != null) {
            this.animal = animal;
            carregarDadosEdicao(this.animal);
            isEdicao = true;
        }        
    }
    
    public void carregarRacas() {
        List<Raca> racas = controller.buscarRacas();
        for (Raca r : racas) {
            jComboBoxRacas.addItem(r);
        }
    }
    
    public void carregarClientes() {
        List<Cliente> clientes = controller.buscarClientes();
        for (Cliente c : clientes) {
            jComboBoxClientes.addItem(c);
        }
    }
    
    public void carregarDadosEdicao(Animal animal) {
        jTextFieldCodigoAnimal.setText(Integer.toString(animal.getCodigo()));
        jTextFieldNomeAnimal.setText(animal.getNome());
        
        for (int i = 0; i < jComboBoxRacas.getItemCount(); i++) {
            if (animal.getRaca().getNome().equals(jComboBoxRacas.getItemAt(i).toString())) {
                jComboBoxRacas.setSelectedIndex(i);
            }
        }
        
        for (int i = 0; i < jComboBoxClientes.getItemCount(); i++) {
            if (animal.getDono().getNome().equals(jComboBoxClientes.getItemAt(i).toString())) {
                jComboBoxClientes.setSelectedIndex(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastrarAnimal = new javax.swing.JPanel();
        jTextFieldCodigoAnimal = new javax.swing.JTextField();
        jTextFieldNomeAnimal = new javax.swing.JTextField();
        jComboBoxRacas = new javax.swing.JComboBox<>();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Animal");

        jPanelCadastrarAnimal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldCodigoAnimal.setEditable(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrarAnimalLayout = new javax.swing.GroupLayout(jPanelCadastrarAnimal);
        jPanelCadastrarAnimal.setLayout(jPanelCadastrarAnimalLayout);
        jPanelCadastrarAnimalLayout.setHorizontalGroup(
            jPanelCadastrarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarAnimalLayout.createSequentialGroup()
                .addGroup(jPanelCadastrarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastrarAnimalLayout.createSequentialGroup()
                        .addComponent(jTextFieldCodigoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRacas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelCadastrarAnimalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );
        jPanelCadastrarAnimalLayout.setVerticalGroup(
            jPanelCadastrarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGravar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastrarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastrarAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:

        animal.setNome(jTextFieldNomeAnimal.getText());
        animal.setRaca((Raca) jComboBoxRacas.getSelectedItem());
        animal.setDono((Cliente) jComboBoxClientes.getSelectedItem());
        if (isEdicao) {
            animal.setCodigo(Integer.parseInt(jTextFieldCodigoAnimal.getText()));
            controller.atualizarAnimal(animal);
        } else {
            controller.inserirAnimal(animal);
            
        }
        this.dispose();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JComboBox<Object> jComboBoxClientes;
    private javax.swing.JComboBox<Object> jComboBoxRacas;
    private javax.swing.JPanel jPanelCadastrarAnimal;
    private javax.swing.JTextField jTextFieldCodigoAnimal;
    private javax.swing.JTextField jTextFieldNomeAnimal;
    // End of variables declaration//GEN-END:variables
}
